// `next-env.d.ts` carries this reference locally, but it is generated by
// `next dev`/`next build` and gitignored, so a clean checkout (CI) has no
// module declarations for the `.svg`/`.png` imports in the editor and
// `pnpm typecheck` fails on every one of them. Referencing the same Next
// types from a tracked file makes typecheck independent of a prior build.
/// <reference types="next/image-types/global" />
